In [520]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import os

In [521]:
matplotlib.rcParams['font.family'] = 'AppleGothic'
matplotlib.rcParams['font.family']

['AppleGothic']

# 불러오기

In [522]:
bedtown_path = '/../../data/clustering_data/침상도시/'
bedtown_list = os.listdir(bedtown_path)
bedtown_list

['거주형태_대구.csv',
 '101_DT_1IN1509_20200831032845.csv',
 '인구통계_대구.csv',
 '인구통계_서울.csv',
 '인구통계_경기.csv',
 '거주형태_경기.csv',
 '거주형태_서울.csv',
 '주택의_종류별_주택읍면동_2015___시군구_2016__20200831032558.csv',
 '시군구별_용도지역별_이용상황별_지가변동률_20200831032029.csv',
 '인구__가구_및_주택__읍면동_2015___시군구_2016__20200831032756.csv']

In [523]:
#불러오기
residence_Daegu = pd.read_csv(bedtown_path+'거주형태_대구.csv', encoding = 'CP949', header = 1)
residence_Seoul = pd.read_csv(bedtown_path+'거주형태_서울.csv', encoding = 'CP949', header = 1)
residence_Gyeongi = pd.read_csv(bedtown_path+'거주형태_경기.csv', encoding = 'CP949', header = 1)

demography_Daegu = pd.read_csv(bedtown_path+'인구통계_대구.csv', encoding = 'CP949', header = 1)
demography_Seoul = pd.read_csv(bedtown_path+'인구통계_서울.csv', encoding = 'CP949').drop(['Unnamed: 6','단위'], axis = 1)
demography_Gyeongi = pd.read_csv(bedtown_path+'인구통계_경기.csv', encoding = 'CP949').drop(['Unnamed: 6','단위'], axis = 1)

In [524]:
#거주형태
residence_주택_Daegu = residence_Daegu[residence_Daegu.거처의종류 == '주택'][['행정구역별(시군구)','거처']]
residence_주택_Seoul = residence_Seoul[residence_Seoul.거처의종류 == '주택'][['행정구역별(시군구)','거처']]
residence_주택_Gyeongi = residence_Gyeongi[residence_Gyeongi.거처의종류 == '주택'][['행정구역별(시군구)','거처']]

residence_주택_Daegu.columns = ['행정구역별(시군구)', '주택']
residence_주택_Seoul.columns = ['행정구역별(시군구)', '주택']
residence_주택_Gyeongi.columns = ['행정구역별(시군구)', '주택']

In [525]:
residence_주택_Daegu['전체대비주택비율'] = residence_주택_Daegu.주택/759619 #대구전체 주택수
residence_주택_Seoul['전체대비주택비율'] = residence_주택_Seoul.주택/2860562
residence_주택_Gyeongi['전체대비주택비율'] = residence_주택_Gyeongi.주택/4075961

In [526]:
area_Daegu = pd.read_csv('/../../data/clustering_data/대구_e지표_정리.csv').drop(['Unnamed: 0'], axis = 1)[['지역별','도시지역면적']]
area_Seoul = pd.read_csv('/../../data/clustering_data/서울_e지표_정리.csv').drop(['Unnamed: 0'], axis = 1)[['지역별','도시지역면적']]
area_Gyeongi = pd.read_csv('/../../data/clustering_data/경기_e지표_정리.csv').drop(['Unnamed: 0'], axis = 1)[['지역별','도시지역면적']]

area_Daegu.columns = ['행정구역별(시군구)','도시지역면적']
area_Seoul.columns = ['행정구역별(시군구)','도시지역면적']
area_Gyeongi.columns = ['행정구역별(시군구)','도시지역면적']

residence_주택_Daegu = pd.merge(area_Daegu,residence_주택_Daegu)
residence_주택_Seoul = pd.merge(area_Seoul,residence_주택_Seoul)
residence_주택_Gyeongi = pd.merge(area_Gyeongi,residence_주택_Gyeongi)

residence_주택_Daegu['면적대비주택비율'] = residence_주택_Daegu.apply(lambda x : (x['주택']/ x['도시지역면적']), axis = 1)
residence_주택_Seoul['면적대비주택비율'] = residence_주택_Seoul.apply(lambda x : (x['주택']/ x['도시지역면적']), axis = 1)
residence_주택_Gyeongi['면적대비주택비율'] = residence_주택_Gyeongi.apply(lambda x : (x['주택']/ x['도시지역면적']), axis = 1)

In [527]:
#인구통계
df1 = demography_Daegu[demography_Daegu.성별 == '계'][['행정구역별(시군구)','연령별','일반가구원']]

demography_Seoul = demography_Seoul[demography_Seoul.성별 == '계']
df2 = demography_Seoul[demography_Seoul.항목 == '일반가구원'][['행정구역별(시군구)','연령별','2019 년']]

demography_Gyeongi = demography_Gyeongi[demography_Gyeongi.성별 == '계']
df3 = demography_Gyeongi[demography_Gyeongi.항목 == '일반가구원'][['행정구역별(시군구)','연령별','2019 년']]

In [528]:
demography_가구원_Daegu = df1.set_index(['연령별','행정구역별(시군구)']).unstack('연령별').reset_index()
demography_가구원_Seoul = df2.set_index(['연령별','행정구역별(시군구)']).unstack('연령별').reset_index()
demography_가구원_Gyeongi = df3.set_index(['연령별','행정구역별(시군구)']).unstack('연령별').reset_index()

demography_가구원_Daegu.columns = demography_가구원_Daegu.columns.droplevel([0])
demography_가구원_Seoul.columns = demography_가구원_Seoul.columns.droplevel([0])
demography_가구원_Gyeongi.columns = demography_가구원_Gyeongi.columns.droplevel([0])

demography_가구원_Daegu.columns = ['행정구역별(시군구)', '15~19세', '15세미만', '20~24세', '25~29세', '30~34세', '35~39세', '40~44세',
       '45~49세', '50~54세', '55~59세', '60~64세', '65~69세', '70~74세', '75~79세',
       '80~84세', '85세이상', '합계']
demography_가구원_Seoul.columns = ['행정구역별(시군구)', '15~19세', '15세미만', '20~24세', '25~29세', '30~34세', '35~39세', '40~44세',
       '45~49세', '50~54세', '55~59세', '60~64세', '65~69세', '70~74세', '75~79세',
       '80~84세', '85세이상', '합계']
demography_가구원_Gyeongi.columns = ['행정구역별(시군구)', '15~19세', '15세미만', '20~24세', '25~29세', '30~34세', '35~39세', '40~44세',
       '45~49세', '50~54세', '55~59세', '60~64세', '65~69세', '70~74세', '75~79세',
       '80~84세', '85세이상', '합계']

In [529]:
df_Daegu = pd.merge(residence_주택_Daegu[:],demography_가구원_Daegu)
df_Seoul = pd.merge(residence_주택_Seoul[:],demography_가구원_Seoul)
df_Gyeongi = pd.merge(residence_주택_Gyeongi[:],demography_가구원_Gyeongi)

df_Seoul.iloc[:,1:] = df_Seoul.iloc[:,1:].apply(pd.to_numeric)
df_Gyeongi.iloc[:,1:] = df_Gyeongi.iloc[:,1:].apply(pd.to_numeric)

In [530]:
#df_Seoul.info()
#df_Gyeongi.info()

In [531]:
df_list = [df_Daegu,df_Seoul,df_Gyeongi]
for df in df_list:
    #print(df)
    df['미성년'] = df['15~19세']+df['15세미만']
    df['청년'] = df['20~24세']+df['25~29세']+df['30~34세']
    df['중년'] = df['35~39세']+df['40~44세']+df['45~49세']
    df['장년'] = df['50~54세']+df['55~59세']+df['60~64세']
    df['노년'] = df['65~69세']+df['70~74세']+df['75~79세']+df['80~84세']+df['85세이상']
    
    df['미성년비율'] = df.apply(lambda x : x['미성년']/ x['합계'], axis = 1)
    df['청년비율'] = df.apply(lambda x : x['청년']/ x['합계'], axis = 1)
    df['중년비율'] = df.apply(lambda x : x['중년']/ x['합계'], axis = 1)
    df['장년비율'] = df.apply(lambda x : x['장년']/ x['합계'], axis = 1)
    df['노년비율'] = df.apply(lambda x : x['노년']/ x['합계'], axis = 1)

In [532]:
df_Daegu = df_Daegu[['행정구역별(시군구)', '주택', '전체대비주택비율','면적대비주택비율','미성년비율', '청년비율', '중년비율', '장년비율', '노년비율']]
df_Seoul = df_Seoul[['행정구역별(시군구)', '주택', '전체대비주택비율','면적대비주택비율','미성년비율', '청년비율', '중년비율', '장년비율', '노년비율']]
df_Gyeongi = df_Gyeongi[['행정구역별(시군구)', '주택', '전체대비주택비율','면적대비주택비율','미성년비율', '청년비율', '중년비율', '장년비율', '노년비율']]

In [533]:
df_Daegu.to_csv("대구_주택과연령비율.csv", mode='w')
df_Seoul.to_csv("서울_주택과연령비율.csv", mode='w')
df_Gyeongi.to_csv("경기_주택과연령비율.csv", mode='w')

In [534]:
df_Gyeongi

,행정구역별(시군구),주택,전체대비주택비율,면적대비주택비율,미성년비율,청년비율,중년비율,장년비율,노년비율
0,가평군,21820,0.005353,0.000266,0.136437,0.133758,0.186212,0.296548,0.247045
1,고양시,313254,0.076854,0.001614,0.182635,0.184406,0.253629,0.251385,0.127944
2,과천시,12927,0.003172,0.000361,0.189792,0.182328,0.233121,0.254748,0.140010
3,광명시,99721,0.024466,0.002590,0.186101,0.182426,0.259265,0.242419,0.129789
4,광주시,115372,0.028305,0.000670,0.188570,0.176507,0.271328,0.239476,0.124119
5,구리시,57693,0.014154,0.001733,0.179944,0.186969,0.252163,0.254689,0.126236
6,군포시,86794,0.021294,0.002381,0.184449,0.195689,0.248511,0.249794,0.121556
7,김포시,140325,0.034427,0.001377,0.223249,0.159226,0.289969,0.207906,0.119649
8,남양주시,221641,0.054378,0.000914,0.208847,0.158515,0.269458,0.231260,0.131919
9,동두천시,33510,0.008221,0.000998,0.171149,0.161159,0.226589,0.252754,0.188349
10,부천시,255150,0.062599,0.004774,0.165990,0.204109,0.242981,0.263626,0.123295
11,성남시,251281,0.061650,0.001772,0.172351,0.198688,0.253128,0.241703,0.134130
12,수원시,354566,0.086990,0.002926,0.191714,0.217396,0.260891,0.226560,0.103439
13,시흥시,152063,0.037307,0.001126,0.205228,0.197076,0.278705,0.233994,0.084998
14,안산시,193891,0.047569,0.001280,0.176492,0.215499,0.246811,0.261677,0.099521
15,안성시,64859,0.015913,0.000415,0.180539,0.171920,0.241020,0.243491,0.163030
16,안양시,171744,0.042136,0.002937,0.173936,0.200810,0.241278,0.258014,0.125962
17,양주시,74540,0.018288,0.000495,0.199457,0.162150,0.251957,0.240043,0.146394
18,양평군,39985,0.009810,0.000781,0.147969,0.120821,0.197476,0.288979,0.244755
19,여주시,36723,0.009010,0.001407,0.158382,0.148242,0.212312,0.276079,0.204985
20,연천군,15462,0.003793,0.000508,0.141669,0.155783,0.172821,0.275323,0.254404
21,오산시,74061,0.018170,0.001732,0.223281,0.200910,0.293917,0.193453,0.088439
22,용인시,326916,0.080206,0.000842,0.214761,0.171917,0.277829,0.208351,0.127142
23,의왕시,50074,0.012285,0.000927,0.174232,0.193100,0.232630,0.270307,0.129731
24,의정부시,142635,0.034994,0.001748,0.177133,0.187298,0.244418,0.248429,0.142722
25,이천시,68800,0.016879,0.000837,0.198852,0.182991,0.246609,0.235824,0.135724
26,파주시,143059,0.035098,0.001759,0.211882,0.171824,0.264758,0.218798,0.132738
27,평택시,171851,0.042162,0.001137,0.198596,0.193366,0.265432,0.224345,0.118261
28,포천시,49591,0.012167,0.001271,0.154516,0.162418,0.204560,0.297137,0.181368
29,하남시,77390,0.018987,0.000832,0.197821,0.178452,0.277557,0.223201,0.122969
30,화성시,258263,0.063362,0.000813,0.245334,0.187463,0.303381,0.180529,0.083292

In [535]:
df_Daegu

,행정구역별(시군구),주택,전체대비주택비율,면적대비주택비율,미성년비율,청년비율,중년비율,장년비율,노년비율
0,남구,39908,0.052537,0.002289,0.115391,0.194198,0.204700,0.264325,0.221386
1,달서구,177823,0.234095,0.002852,0.178666,0.188972,0.235647,0.264455,0.132259
2,달성군,86550,0.113939,0.000229,0.212588,0.181473,0.267235,0.223864,0.114840
3,동구,114397,0.150598,0.000779,0.159695,0.174310,0.228797,0.252699,0.184499
4,북구,137189,0.180602,0.001460,0.183934,0.193893,0.242655,0.245525,0.133994
5,서구,50331,0.066258,0.002904,0.115751,0.176785,0.197019,0.302515,0.207930
6,수성구,129567,0.170568,0.001693,0.197407,0.158136,0.240829,0.253582,0.150047
7,중구,23854,0.031403,0.003381,0.141206,0.215609,0.222314,0.224466,0.196405