In [1]:
import re
import pandas as pd
from functools import reduce

### 경기도_시군구별_인구수_2019

In [12]:
gg_pop = pd.read_csv('../../data/localdata/gg_pop_2019.csv', encoding='cp949')

In [13]:
#gg_pop

In [14]:
gg_pop.columns

Index(['행정구역(시군구)별', '총인구수 (명)'], dtype='object')

In [15]:
gg_pop.rename(columns = {'행정구역(시군구)별' : '시군'}, inplace = True)

### 경기지역화폐 시군별 특징

In [73]:
gg_lc_feature = pd.read_csv('../../data/localdata/gg_lc_feature.csv')

In [74]:
gg_lc_feature.columns

Index(['시군(개시일)', '할인율', '구매한도(월/연,만원)', '비고'], dtype='object')

In [75]:
gg_lc_feature['개시일'] = gg_lc_feature['시군(개시일)'].apply(lambda x : x.split('(')[1][:-1])
gg_lc_feature['시군(개시일)'] = gg_lc_feature['시군(개시일)'].apply(lambda x : x.split('(')[0])

In [76]:
gg_lc_feature['할인율_상시'] = gg_lc_feature['할인율'].apply(lambda x : int(re.findall('\d+', x)[0]))
gg_lc_feature['할인율_한시'] = gg_lc_feature['할인율'].apply(lambda x : int(re.findall('\d+', x)[1]))
gg_lc_feature = gg_lc_feature.drop('할인율', axis=1)

In [77]:
gg_lc_feature['할인율_상시'] = gg_lc_feature['할인율_상시'].apply(lambda x: float(x)*0.01 if 1<x<11 else None)
gg_lc_feature['할인율_한시'] = gg_lc_feature['할인율_한시'].apply(lambda x: float(x)*0.01 if 1<x<11 else None)

In [78]:
gg_lc_feature['구매한도_월'] = gg_lc_feature['구매한도(월/연,만원)'].apply(lambda x : x.split('/')[0])
gg_lc_feature['구매한도_연'] = gg_lc_feature['구매한도(월/연,만원)'].apply(lambda x : x.split('/')[1])

In [79]:
gg_lc_feature.to_csv('../../data/localdata/gg_lc_feature_1.csv', sep=',')

In [80]:
gg_lc_feature = gg_lc_feature.drop(['구매한도(월/연,만원)','비고','개시일'], axis=1)

In [81]:
gg_lc_feature.rename(columns = {'시군(개시일)' : '시군'}, inplace = True)

In [82]:
gg_lc_feature

      시군  할인율_상시  할인율_한시 구매한도_월 구매한도_연
0    수원시    0.06    0.10     50    400
1    고양시    0.06    0.10     40    400
2    용인시    0.06    0.10     50    600
3    성남시    0.06     NaN     10     50
4    부천시    0.06    0.10     40    400
5    화성시    0.06    0.10     50    600
6    안산시    0.06    0.10      0    400
7   남양주시    0.06    0.10     50    600
8    안양시    0.06    0.10     30    600
9    평택시    0.06    0.10     30    360
10   시흥시    0.05    0.10     40    480
11   파주시    0.06    0.10     40    400
12  의정부시    0.06    0.10     40    400
13  김포시     0.06    0.10     50    600
14   광주시    0.06     NaN     40    400
15   광명시    0.06    0.10     40    480
16   군포시    0.06    0.10     50    600
17   하남시    0.06    0.10     50    600
18   오산시    0.06    0.10     30    360
19   이천시    0.06    0.10     40    400
20   양주시    0.06    0.10     50    600
21   구리시    0.06    0.10     50    600
22   안성시    0.06    0.10     50    500
23   포천시    0.06    0.10     30    360
24   의왕시    0.06    0.10     40    400
25   양평군    0.10     NaN     50    500
26   여주시    0.06    0.09     40    400
27  동두천시    0.06    0.10     30    360
28   가평군    0.06    0.10     30    360
29   과천시    0.06    0.10     40    480
30   연천군    0.06    0.10     50    600

### 경기지역화폐 발행 및 이용현황

In [83]:
gg_lc_current_state = pd.read_csv('../../data/localdata/gg_lc_current_state.csv',
                                 encoding='cp949')

In [84]:
#gg_lc_current_state

In [85]:
gg_lc_current_state['년도'] = gg_lc_current_state['기준년월'].apply(lambda x : x.split('-')[0])
gg_lc_current_state_2019 = gg_lc_current_state[gg_lc_current_state['년도'] == '2019']

In [86]:
sum_gg_lc = gg_lc_current_state_2019.groupby('시군명').sum().fillna(0)

In [87]:
sum_gg_lc.reset_index(level=['시군명'], inplace = True)

In [88]:
sum_gg_lc.rename(columns = {'시군명' : '시군'}, inplace = True)

In [89]:
sum_gg_lc

,시군,월별카드발행수량(건),월별카드충전액(천원),월별카드사용액(천원),월별모바일상품권이용등록자수(명),월별모바일충전액(천원),월별모바일사용액(천원),월별지류상품권판매액(천원),월별지류상품권회수액(천원)
0,가평군,2714.0,1389589.0,1163080.0,0.0,0.0,0.0,1082460.0,1131340.0
1,고양시,58907.0,39138171.0,28739326.0,0.0,0.0,0.0,0.0,0.0
2,과천시,6944.0,3980845.0,3321976.0,0.0,0.0,0.0,3942210.0,3361215.0
3,광명시,15574.0,7869194.0,6372380.0,0.0,0.0,0.0,0.0,0.0
4,광주시,17652.0,9426901.0,7557041.0,0.0,0.0,0.0,0.0,0.0
5,구리시,10354.0,5366257.0,4011320.0,0.0,0.0,0.0,0.0,0.0
6,군포시,22534.0,19785128.0,16642604.0,0.0,0.0,0.0,0.0,0.0
7,김포시,0.0,0.0,0.0,64448.0,32001938.0,28981268.0,0.0,0.0
8,남양주시,29786.0,17129388.0,12979396.0,0.0,0.0,0.0,0.0,0.0
9,동두천시,5392.0,2582608.0,2106819.0,0.0,0.0,0.0,0.0,0.0
10,부천시,66397.0,37236768.0,31543254.0,0.0,0.0,0.0,0.0,0.0
11,성남시,0.0,69427717.0,60660081.0,30042.0,5981565.0,4558769.0,18763560.0,20855220.0
12,수원시,62464.0,29413908.0,22696236.0,0.0,0.0,0.0,0.0,0.0
13,시흥시,0.0,0.0,0.0,50500.0,27566330.0,21329128.0,10708962.0,9215278.0
14,안산시,37292.0,22597197.0,18936420.0,0.0,0.0,0.0,10133785.0,8099925.0
15,안성시,11249.0,9939110.0,8509106.0,0.0,0.0,0.0,0.0,0.0
16,안양시,16180.0,8160695.0,5689123.0,0.0,0.0,0.0,15431185.0,14702685.0
17,양주시,13667.0,10012354.0,8292230.0,0.0,0.0,0.0,0.0,0.0
18,양평군,9067.0,9451448.0,8659833.0,0.0,0.0,0.0,0.0,0.0
19,여주시,6158.0,3533706.0,2898929.0,0.0,0.0,0.0,0.0,0.0
20,연천군,4518.0,2752155.0,2183752.0,0.0,0.0,0.0,0.0,0.0
21,오산시,14407.0,7380922.0,6017615.0,0.0,0.0,0.0,0.0,0.0
22,용인시,40516.0,20772052.0,15960062.0,0.0,0.0,0.0,0.0,0.0
23,의왕시,4228.0,2125104.0,1494962.0,0.0,0.0,0.0,5500000.0,4929585.0
24,의정부시,21717.0,11583048.0,9062650.0,0.0,0.0,0.0,0.0,0.0
25,이천시,11158.0,6741471.0,5020770.0,0.0,0.0,0.0,0.0,0.0
26,파주시,22798.0,11019127.0,8462572.0,0.0,0.0,0.0,0.0,0.0
27,평택시,8711.0,4527945.0,3379155.0,0.0,0.0,0.0,9386280.0,7164405.0
28,포천시,4163.0,1696449.0,1220732.0,0.0,0.0,0.0,1518425.0,1157000.0
29,하남시,19623.0,16659230.0,14538314.0,0.0,0.0,0.0,0.0,0.0
30,화성시,43350.0,27496806.0,22496907.0,0.0,0.0,0.0,0.0,0.0

### 경기도 시군별 경제활동인구

In [90]:
gg_economic_pop_2019 = pd.read_csv('../../data/localdata/gg_economic_pop_2019.csv',
                                  encoding='cp949')

In [91]:
gg_economic_pop_rate = gg_economic_pop_2019[['행정구역별','경제활동참가율 (％)']]

In [92]:
gg_economic_pop_rate.rename(columns = {'행정구역별' : '시군','경제활동참가율 (％)' : '경제활동참가율'}, inplace = True)

C:\Users\smk\Anaconda3\lib\site-packages\pandas\core\frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [93]:
gg_economic_pop_rate

      시군  경제활동참가율
0    수원시     62.6
1    성남시     62.0
2   의정부시     59.4
3    안양시     62.1
4    부천시     63.0
5    광명시     61.8
6    평택시     63.8
7   동두천시     56.2
8    안산시     63.4
9    고양시     59.7
10   과천시     55.3
11   구리시     60.5
12  남양주시     57.8
13   오산시     64.1
14   시흥시     66.2
15   군포시     61.8
16   의왕시     59.4
17   하남시     64.0
18   용인시     59.2
19   파주시     61.0
20   이천시     66.3
21   안성시     66.5
22   김포시     63.4
23   화성시     68.2
24   광주시     62.5
25   양주시     59.9
26   포천시     65.7
27   여주시     61.4
28   연천군     64.5
29   가평군     62.1
30   양평군     62.6

### merge

In [94]:
# gg_pop['행정구역(시군구)별'], gg_lc_feature['시군(개시일)'], sum_gg_lc['시군명'], gg_economic_pop_rate['행정구역별']
# dfs = [df1, df2, df3, dfN]
# df_merge = reduce(lambda left, right: pd.merge(left, right, on='시군'), dfs)
dfs = [gg_pop, gg_lc_feature, sum_gg_lc, gg_economic_pop_rate]
df_merge = reduce(lambda left, right: pd.merge(left, right, on='시군'), dfs)

In [95]:
df_merge

,시군,총인구수 (명),할인율_상시,할인율_한시,구매한도_월,구매한도_연,월별카드발행수량(건),월별카드충전액(천원),월별카드사용액(천원),월별모바일상품권이용등록자수(명),월별모바일충전액(천원),월별모바일사용액(천원),월별지류상품권판매액(천원),월별지류상품권회수액(천원),경제활동참가율
0,수원시,1194465,0.06,0.10,50,400,62464.0,29413908.0,22696236.0,0.0,0.0,0.0,0.0,0.0,62.6
1,성남시,942724,0.06,NaN,10,50,0.0,69427717.0,60660081.0,30042.0,5981565.0,4558769.0,18763560.0,20855220.0,62.0
2,의정부시,451868,0.06,0.10,40,400,21717.0,11583048.0,9062650.0,0.0,0.0,0.0,0.0,0.0,59.4
3,안양시,567044,0.06,0.10,30,600,16180.0,8160695.0,5689123.0,0.0,0.0,0.0,15431185.0,14702685.0,62.1
4,부천시,829996,0.06,0.10,40,400,66397.0,37236768.0,31543254.0,0.0,0.0,0.0,0.0,0.0,63.0
5,광명시,316552,0.06,0.10,40,480,15574.0,7869194.0,6372380.0,0.0,0.0,0.0,0.0,0.0,61.8
6,평택시,513027,0.06,0.10,30,360,8711.0,4527945.0,3379155.0,0.0,0.0,0.0,9386280.0,7164405.0,63.8
7,동두천시,94768,0.06,0.10,30,360,5392.0,2582608.0,2106819.0,0.0,0.0,0.0,0.0,0.0,56.2
8,안산시,650918,0.06,0.10,0,400,37292.0,22597197.0,18936420.0,0.0,0.0,0.0,10133785.0,8099925.0,63.4
9,고양시,1066351,0.06,0.10,40,400,58907.0,39138171.0,28739326.0,0.0,0.0,0.0,0.0,0.0,59.7
10,과천시,58289,0.06,0.10,40,480,6944.0,3980845.0,3321976.0,0.0,0.0,0.0,3942210.0,3361215.0,55.3
11,구리시,199265,0.06,0.10,50,600,10354.0,5366257.0,4011320.0,0.0,0.0,0.0,0.0,0.0,60.5
12,남양주시,701830,0.06,0.10,50,600,29786.0,17129388.0,12979396.0,0.0,0.0,0.0,0.0,0.0,57.8
13,오산시,226379,0.06,0.10,30,360,14407.0,7380922.0,6017615.0,0.0,0.0,0.0,0.0,0.0,64.1
14,시흥시,473682,0.05,0.10,40,480,0.0,0.0,0.0,50500.0,27566330.0,21329128.0,10708962.0,9215278.0,66.2
15,군포시,275852,0.06,0.10,50,600,22534.0,19785128.0,16642604.0,0.0,0.0,0.0,0.0,0.0,61.8
16,의왕시,161153,0.06,0.10,40,400,4228.0,2125104.0,1494962.0,0.0,0.0,0.0,5500000.0,4929585.0,59.4
17,하남시,272455,0.06,0.10,50,600,19623.0,16659230.0,14538314.0,0.0,0.0,0.0,0.0,0.0,64.0
18,용인시,1059609,0.06,0.10,50,600,40516.0,20772052.0,15960062.0,0.0,0.0,0.0,0.0,0.0,59.2
19,파주시,454040,0.06,0.10,40,400,22798.0,11019127.0,8462572.0,0.0,0.0,0.0,0.0,0.0,61.0
20,이천시,215834,0.06,0.10,40,400,11158.0,6741471.0,5020770.0,0.0,0.0,0.0,0.0,0.0,66.3
21,안성시,183405,0.06,0.10,50,500,11249.0,9939110.0,8509106.0,0.0,0.0,0.0,0.0,0.0,66.5
22,화성시,815396,0.06,0.10,50,600,43350.0,27496806.0,22496907.0,0.0,0.0,0.0,0.0,0.0,68.2
23,광주시,372654,0.06,NaN,40,400,17652.0,9426901.0,7557041.0,0.0,0.0,0.0,0.0,0.0,62.5
24,양주시,222314,0.06,0.10,50,600,13667.0,10012354.0,8292230.0,0.0,0.0,0.0,0.0,0.0,59.9
25,포천시,148379,0.06,0.10,30,360,4163.0,1696449.0,1220732.0,0.0,0.0,0.0,1518425.0,1157000.0,65.7
26,여주시,111083,0.06,0.09,40,400,6158.0,3533706.0,2898929.0,0.0,0.0,0.0,0.0,0.0,61.4
27,연천군,43824,0.06,0.10,50,600,4518.0,2752155.0,2183752.0,0.0,0.0,0.0,0.0,0.0,64.5
28,가평군,62415,0.06,0.10,30,360,2714.0,1389589.0,1163080.0,0.0,0.0,0.0,1082460.0,1131340.0,62.1
29,양평군,116874,0.10,NaN,50,500,9067.0,9451448.0,8659833.0,0.0,0.0,0.0,0.0,0.0,62.6